version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: "Asia/Shanghai"
    day: "sunday"
  open-pull-requests-limit: 5
  rebase-strategy: "auto"
  
